// Monster names and challenge ratings from the 2024 Monster Manual on Demiplane.
// Kept as a standalone catalog so future encounter calculations can reuse it.
window.MONSTERS_BY_CR = Object.freeze({
  "0": ["Awakened Shrub", "Baboon", "Badger", "Bat", "Cat", "Commoner", "Crab", "Crawling Claw", "Deer", "Eagle", "Frog", "Giant Fire Beetle", "Goat", "Hawk", "Homunculus", "Hyena", "Jackal", "Larva", "Lemure", "Lizard", "Myconid Sprout", "Octopus", "Owl", "Piranha", "Rat", "Raven", "Scorpion", "Seahorse", "Shrieker Fungus", "Spider", "Vulture", "Weasel"],
  "1/8": ["Bandit", "Blood Hawk", "Camel", "Cultist", "Flumph", "Flying Snake", "Giant Crab", "Giant Rat", "Giant Weasel", "Goblin Minion", "Guard", "Kobold Warrior", "Manes", "Mastiff", "Merfolk Skirmisher", "Modron Monodrone", "Mule", "Noble", "Pony", "Slaad Tadpole", "Stirge", "Twig Blight", "Venomous Snake", "Warrior Infantry"],
  "1/4": ["Aarakocra Skirmisher", "Animated Broom", "Animated Flying Sword", "Axe Beak", "Blink Dog", "Boar", "Bullywug Warrior", "Constrictor Snake", "Draft Horse", "Dretch", "Elk", "Giant Badger", "Giant Bat", "Giant Centipede", "Giant Frog", "Giant Lizard", "Giant Owl", "Giant Venomous Snake", "Giant Wolf Spider", "Goblin Warrior", "Grimlock", "Kenku", "Kuo-toa", "Modron Duodrone", "Mud Mephit", "Needle Blight", "Panther", "Pixie", "Priest Acolyte", "Pseudodragon", "Pteranodon", "Riding Horse", "Skeleton", "Smoke Mephit", "Sprite", "Steam Mephit", "Swarm of Bats", "Swarm of Rats", "Swarm of Ravens", "Troglodyte", "Violet Fungus", "Winged Kobold", "Wolf", "Zombie"],
  "1/2": ["Ape", "Black Bear", "Cockatrice", "Crocodile", "Darkmantle", "Dust Mephit", "Gas Spore Fungus", "Giant Goat", "Giant Seahorse", "Giant Wasp", "Gnoll Warrior", "Gray Ooze", "Hobgoblin Warrior", "Ice Mephit", "Jackalwere", "Magma Mephit", "Magmin", "Modron Tridrone", "Myconid Adult", "Performer", "Piercer", "Reef Shark", "Rust Monster", "Sahuagin Warrior", "Satyr", "Scout", "Shadow", "Swarm of Insects", "Tough", "Troll Limb", "Vine Blight", "Warhorse", "Warhorse Skeleton", "Worg"],
  "1": ["Animated Armor", "Brass Dragon Wyrmling", "Brown Bear", "Bugbear Warrior", "Copper Dragon Wyrmling", "Death Dog", "Dire Wolf", "Dryad", "Empyrean Iota", "Faerie Dragon Youth", "Ghoul", "Giant Eagle", "Giant Hyena", "Giant Octopus", "Giant Spider", "Giant Toad", "Giant Vulture", "Goblin Boss", "Harpy", "Hippogriff", "Imp", "Kuo-toa Whip", "Lacedon Ghoul", "Lion", "Manes Vaporspawn", "Modron Quadrone", "Myconid Spore Servant", "Ogrillon Ogre", "Pirate", "Psychic Gray Ooze", "Quasit", "Salamander Fire Snake", "Scarecrow", "Specter", "Sphinx of Wonder", "Spy", "Swarm of Larvae", "Swarm of Piranhas", "Thri-kreen Marauder", "Tiger", "Yuan-ti Infiltrator"],
  "2": ["Allosaurus", "Animated Rug of Smothering", "Ankheg", "Awakened Tree", "Azer Sentinel", "Bandit Captain", "Berserker", "Black Dragon Wyrmling", "Bronze Dragon Wyrmling", "Bulette Pup", "Carrion Crawler", "Centaur Trooper", "Cultist Fanatic", "Druid", "Ettercap", "Faerie Dragon Adult", "Gargoyle", "Gelatinous Cube", "Ghast", "Giant Boar", "Giant Constrictor Snake", "Giant Elk", "Gibbering Mouther", "Githzerai Monk", "Gnoll Pack Lord", "Green Dragon Wyrmling", "Grick", "Griffon", "Hunter Shark", "Intellect Devourer", "Lizardfolk Geomancer", "Mage Apprentice", "Merrow", "Mimic", "Minotaur Skeleton", "Modron Pentadrone", "Myconid Sovereign", "Nothic", "Ochre Jelly", "Ogre", "Ogre Zombie", "Pegasus", "Peryton", "Plesiosaurus", "Polar Bear", "Poltergeist", "Priest", "Quaggoth", "Rhinoceros", "Saber-Toothed Tiger", "Sahuagin Priest", "Sea Hag", "Silver Dragon Wyrmling", "Spined Devil", "Swarm of Stirges", "Swarm of Venomous Snakes", "Wererat", "White Dragon Wyrmling", "Will-o’-Wisp"],
  "3": ["Ankylosaurus", "Basilisk", "Bearded Devil", "Blue Dragon Wyrmling", "Bugbear Stalker", "Displacer Beast", "Doppelganger", "Flaming Skeleton", "Giant Scorpion", "Githyanki Warrior", "Goblin Hexer", "Gold Dragon Wyrmling", "Green Hag", "Grell", "Hell Hound", "Hobgoblin Captain", "Hook Horror", "Killer Whale", "Knight", "Kuo-toa Monitor", "Manticore", "Minotaur of Baphomet", "Mummy", "Nightmare", "Owlbear", "Phase Spider", "Quaggoth Thonot", "Scout Captain", "Spectator", "Swarm of Crawling Claws", "Swarm of Lemures", "Vampire Familiar", "Warrior Veteran", "Water Weird", "Werewolf", "Wight", "Winter Wolf", "Yeti", "Yuan-ti Malison (Type 1)", "Yuan-ti Malison (Type 2)", "Yuan-ti Malison (Type 3)"],
  "4": ["Aarakocra Aeromancer", "Archelon", "Banshee", "Black Pudding", "Bone Naga", "Bullywug Bog Sage", "Chuul", "Couatl", "Elephant", "Ettin", "Flameskull", "Ghost", "Gnoll Fang of Yeenoghu", "Guard Captain", "Helmed Horror", "Hippopotamus", "Incubus", "Juvenile Shadow Dragon", "Lamia", "Lizardfolk Sovereign", "Red Dragon Wyrmling", "Shadow Demon", "Succubus", "Swarm of Dretches", "Tough Boss", "Wereboar", "Weretiger"],
  "5": ["Air Elemental", "Barbed Devil", "Barlgura", "Beholder Zombie", "Bulette", "Cambion", "Earth Elemental", "Fire Elemental", "Flesh Golem", "Giant Axe Beak", "Giant Crocodile", "Giant Shark", "Gladiator", "Gorgon", "Half-Dragon", "Hill Giant", "Mezzoloth", "Night Hag", "Otyugh", "Pixie Wonderbringer", "Red Slaad", "Revenant", "Roper", "Sahuagin Baron", "Salamander", "Shambling Mound", "Triceratops", "Troll", "Umber Hulk", "Unicorn", "Vampire Spawn", "Water Elemental", "Werebear", "Wraith", "Xorn", "Young Remorhaz"],
  "6": ["Azer Pyromancer", "Chasme", "Chimera", "Cyclops Sentry", "Drider", "Galeb Duhr", "Ghast Gravecaller", "Giant Squid", "Githzerai Zerth", "Hobgoblin Warlord", "Invisible Stalker", "Kuo-toa Archpriest", "Mage", "Mammoth", "Medusa", "Merfolk Wavebender", "Performer Maestro", "Pirate Captain", "Satyr Revelmaster", "Vrock", "Wyvern", "Young Brass Dragon", "Young White Dragon"],
  "7": ["Bandit Deceiver", "Blue Slaad", "Centaur Warden", "Giant Ape", "Graveyard Revenant", "Grick Ancient", "Mind Flayer", "Oni", "Primeval Owlbear", "Shield Guardian", "Stone Giant", "Tree Blight", "Violet Fungus Necrohulk", "Young Black Dragon", "Young Copper Dragon", "Yuan-ti Abomination"],
  "8": ["Aberrant Cultist", "Assassin", "Berserker Commander", "Chain Devil", "Cloaker", "Cockatrice Regent", "Death Cultist", "Elemental Cultist", "Fiend Cultist", "Fomorian", "Frost Giant", "Githyanki Knight", "Gnoll Demoniac", "Green Slaad", "Hezrou", "Hydra", "Sphinx of Secrets", "Spirit Naga", "Thri-kreen Psion", "Tyrannosaurus Rex", "Vampire Nightbringer", "Young Bronze Dragon", "Young Green Dragon"],
  "9": ["Abominable Yeti", "Bone Devil", "Brazen Gorgon", "Clay Golem", "Cloud Giant", "Fire Giant", "Glabrezu", "Gray Slaad", "Nycaloth", "Treant", "Young Blue Dragon", "Young Silver Dragon"],
  "10": ["Aboleth", "Cultist Hierophant", "Cyclops Oracle", "Death Slaad", "Deva", "Dire Worg", "Guardian Naga", "Haunting Revenant", "Noble Prodigy", "Performer Legend", "Spy Master", "Stone Golem", "Warrior Commander", "Yochlol", "Young Gold Dragon", "Young Red Dragon"],
  "11": ["Bandit Crime Lord", "Behir", "Dao", "Death Knight Aspirant", "Djinni", "Efreeti", "Horned Devil", "Marid", "Mind Flayer Arcanist", "Remorhaz", "Roc", "Sphinx of Lore"],
  "12": ["Arcanaloth", "Archmage", "Archpriest", "Erinyes", "Githzerai Psion", "Pirate Admiral", "Questing Knight"],
  "13": ["Adult Brass Dragon", "Adult White Dragon", "Beholder", "Nalfeshnee", "Rakshasa", "Shadow Dragon", "Storm Giant", "Ultroloth", "Vampire"],
  "14": ["Adult Black Dragon", "Adult Copper Dragon", "Death Tyrant", "Ice Devil"],
  "15": ["Adult Bronze Dragon", "Adult Green Dragon", "Mummy Lord", "Purple Worm", "Salamander Inferno Master", "Vampire Umbral Lord"],
  "16": ["Adult Blue Dragon", "Adult Silver Dragon", "Githyanki Dracomancer", "Gulthias Blight", "Iron Golem", "Marilith", "Planetar"],
  "17": ["Adult Gold Dragon", "Adult Red Dragon", "Death Knight", "Dracolich", "Dragon Turtle", "Goristro", "Sphinx of Valor"],
  "18": ["Demilich"],
  "19": ["Balor"],
  "20": ["Ancient Brass Dragon", "Ancient White Dragon", "Animal Lord", "Pit Fiend"],
  "21": ["Ancient Black Dragon", "Ancient Copper Dragon", "Arch-hag", "Lich", "Solar"],
  "22": ["Ancient Bronze Dragon", "Ancient Green Dragon", "Elemental Cataclysm"],
  "23": ["Ancient Blue Dragon", "Ancient Silver Dragon", "Blob of Annihilation", "Empyrean", "Kraken"],
  "24": ["Ancient Gold Dragon", "Ancient Red Dragon"],
  "25": ["Colossus"],
  "30": ["Tarrasque"]
});

// Monster Manual treasure tags. Names omitted from these groups are tagged "None".
window.MONSTER_TREASURE_GROUPS = Object.freeze({
  "Any": ["Abominable Yeti", "Adult Red Dragon", "Ancient Red Dragon", "Bandit", "Bandit Captain", "Bandit Crime Lord", "Bandit Deceiver", "Barbed Devil", "Barlgura", "Basilisk", "Behir", "Blob of Annihilation", "Blue Slaad", "Brazen Gorgon", "Chimera", "Death Slaad", "Death Tyrant", "Dracolich", "Dragon Turtle", "Dryad", "Fomorian", "Galeb Duhr", "Gargoyle", "Gelatinous Cube", "Ghast", "Ghast Gravecaller", "Ghost", "Ghoul", "Gorgon", "Graveyard Revenant", "Gray Slaad", "Green Slaad", "Grick", "Grick Ancient", "Grimlock", "Harpy", "Haunting Revenant", "Hezrou", "Hydra", "Incubus", "Iron Golem", "Juvenile Shadow Dragon", "Kraken", "Lacedon Ghoul", "Manticore", "Medusa", "Merrow", "Mimic", "Myconid Adult", "Myconid Sovereign", "Myconid Spore Servant", "Myconid Sprout", "Otyugh", "Phase Spider", "Poltergeist", "Red Dragon Wyrmling", "Red Slaad", "Revenant", "Roc", "Roper", "Sahuagin Baron", "Sahuagin Priest", "Sahuagin Warrior", "Shadow Dragon", "Slaad Tadpole", "Solar", "Spectator", "Unicorn", "Vampire", "Vampire Familiar", "Vampire Nightbringer", "Vampire Spawn", "Vampire Umbral Lord", "Water Weird", "Werewolf", "Wyvern", "Xorn", "Yeti", "Young Red Dragon"],
  "Arcana": ["Adult Brass Dragon", "Adult Copper Dragon", "Adult Gold Dragon", "Adult Green Dragon", "Adult Silver Dragon", "Adult White Dragon", "Ancient Brass Dragon", "Ancient Copper Dragon", "Ancient Gold Dragon", "Ancient Green Dragon", "Ancient Silver Dragon", "Ancient White Dragon", "Arcanaloth", "Arch-hag", "Beholder", "Brass Dragon Wyrmling", "Cloud Giant", "Copper Dragon Wyrmling", "Demilich", "Djinni", "Flameskull", "Flesh Golem", "Flumph", "Gold Dragon Wyrmling", "Green Dragon Wyrmling", "Green Hag", "Ice Devil", "Lamia", "Lich", "Mind Flayer", "Mind Flayer Arcanist", "Night Hag", "Nothic", "Pixie", "Pixie Wonderbringer", "Pseudodragon", "Sea Hag", "Silver Dragon Wyrmling", "Sphinx of Lore", "Sphinx of Secrets", "Sphinx of Valor", "Sphinx of Wonder", "Spirit Naga", "White Dragon Wyrmling", "Young Brass Dragon", "Young Copper Dragon", "Young Gold Dragon", "Young Green Dragon", "Young Silver Dragon", "Young White Dragon"],
  "Arcana, Individual": ["Archmage", "Githzerai Monk", "Githzerai Psion", "Githzerai Zerth", "Mage", "Mage Apprentice"],
  "Armaments": ["Balor", "Bearded Devil", "Cyclops Oracle", "Cyclops Sentry", "Death Knight", "Death Knight Aspirant", "Drider", "Efreeti", "Erinyes", "Fire Giant", "Frost Giant", "Githyanki Dracomancer", "Githyanki Knight", "Githyanki Warrior", "Goristro", "Half-Dragon", "Helmed Horror", "Hill Giant", "Kobold Warrior", "Marilith", "Mezzoloth", "Minotaur of Baphomet", "Nycaloth", "Ogre", "Ogrillon Ogre", "Oni", "Peryton", "Salamander", "Salamander Fire Snake", "Salamander Inferno Master", "Sprite", "Stone Giant", "Storm Giant", "Thri-kreen Marauder", "Thri-kreen Psion", "Tough", "Tough Boss", "Troglodyte", "Ultroloth", "Vrock", "Warrior Commander", "Warrior Infantry", "Warrior Veteran", "Weretiger", "Wight", "Winged Kobold"],
  "Armaments, Individual": ["Azer Pyromancer", "Azer Sentinel", "Berserker", "Berserker Commander", "Bugbear Stalker", "Bugbear Warrior", "Centaur Trooper", "Centaur Warden", "Gladiator", "Gnoll Demoniac", "Gnoll Fang of Yeenoghu", "Gnoll Pack Lord", "Gnoll Warrior", "Guard", "Guard Captain", "Hobgoblin Captain", "Hobgoblin Warlord", "Hobgoblin Warrior", "Knight", "Questing Knight"],
  "Implements": ["Adult Bronze Dragon", "Ancient Bronze Dragon", "Bone Devil", "Bronze Dragon Wyrmling", "Chain Devil", "Cloaker", "Dao", "Ettercap", "Faerie Dragon Adult", "Faerie Dragon Youth", "Jackalwere", "Satyr", "Satyr Revelmaster", "Succubus", "Young Bronze Dragon"],
  "Implements, Individual": ["Aarakocra Aeromancer", "Aarakocra Skirmisher", "Assassin", "Bullywug Bog Sage", "Bullywug Warrior", "Goblin Boss", "Goblin Hexer", "Goblin Minion", "Goblin Warrior", "Kenku", "Performer", "Performer Legend", "Performer Maestro", "Scout", "Scout Captain", "Spy", "Spy Master"],
  "Individual": ["Commoner", "Doppelganger", "Ettin", "Lizardfolk Geomancer", "Lizardfolk Sovereign", "Merfolk Skirmisher", "Merfolk Wavebender", "Noble", "Noble Prodigy", "Piercer", "Wereboar", "Wererat"],
  "Individual, Implements": ["Pirate", "Pirate Admiral", "Pirate Captain"],
  "Individual, Relics": ["Aberrant Cultist", "Archpriest", "Cultist", "Cultist Fanatic", "Cultist Hierophant", "Death Cultist", "Druid", "Elemental Cultist", "Fiend Cultist", "Priest", "Priest Acolyte"],
  "Relics": ["Aboleth", "Adult Black Dragon", "Adult Blue Dragon", "Ancient Black Dragon", "Ancient Blue Dragon", "Animal Lord", "Banshee", "Black Dragon Wyrmling", "Blue Dragon Wyrmling", "Bone Naga", "Cambion", "Chasme", "Chuul", "Clay Golem", "Colossus", "Couatl", "Deva", "Empyrean", "Empyrean Iota", "Glabrezu", "Guardian Naga", "Horned Devil", "Kuo-toa", "Kuo-toa Archpriest", "Kuo-toa Monitor", "Kuo-toa Whip", "Marid", "Mummy", "Mummy Lord", "Nalfeshnee", "Pit Fiend", "Planetar", "Rakshasa", "Werebear", "Young Black Dragon", "Young Blue Dragon", "Yuan-ti Abomination", "Yuan-ti Infiltrator", "Yuan-ti Malison (Type 1)", "Yuan-ti Malison (Type 2)", "Yuan-ti Malison (Type 3)"]
});
